% !Rnw root = lumi_qc.Rnw

\\subsubsection{Automatic Outlier Detection}

Outlier detection was performed by looking for arrays for which the mean of the distances to all other arrays was exceptionally large. 

<<outlier_report, echo=FALSE, results="asis">>=
if (length(outliers) == 1) {
  print(length(outliers)+" outlier was discovered by this mechanism.")
} else {
  print(length(outliers)+" outliers were discovered by this mechanism.")
}
@