\documentclass[12pt,BCOR1mm,DIV18]{scrartcl}

\usepackage[backend=bibtex,style=ieee]{biblatex} % references
\usepackage{url}  % Formatting web addresses  

\usepackage[british]{babel}
\usepackage{inputenc}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{makeidx}
\usepackage{booktabs}
\usepackage{lmodern}
\usepackage[T1]{fontenc}
\usepackage{textcomp}
\usepackage{microtype}
\usepackage{tabularx}

\RequirePackage[unicode,hyperfootnotes=false]{hyperref}
 \hypersetup{%
   pdfborder = {0 0 0},
   bookmarksdepth = section,
   citecolor = DarkGreen,
   linkcolor = DarkBlue,
   urlcolor = DarkGreen,
 }%
\urlstyle{rm}
\newcommand{\cc}{\texttt}

\addbibresource{bibtexfile.bib}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%knitr settings
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<setup, include=FALSE, cache=FALSE, concordance=TRUE>>=
opts_chunk$set(fig.path='knitr_graphics/', cache.path='knitr_cache/graphics-', fig.align='center', fig.height=3, tidy.opts=list(width.cutoff=60))

setwd('~/Code/knitr-templates')
Sys.setenv(TEXINPUTS=getwd(),
           BIBINPUTS=getwd(),
           BSTINPUTS=getwd())
@

\raggedbottom
\makeatletter
\makeatother
\makeindex

\begin{document}

\title{{\Large \bf Microarray analysis - a sample summary}}
\author{Simon J. Cockell}
\maketitle

\includegraphics[width=\textwidth]{BSU_header}

\begin{center}
\noindent {\small Bioinformatics Support Unit, Newcastle University, Newcastle upon Tyne, UK.}\\
\noindent {\small \url{http://bsu.ncl.ac.uk/}}\\

\end{center}


\newpage

\Sexpr{knit_child('lumi_summary.Rnw')} %introduction and links to sections
\Sexpr{knit_child('lumi_qc.Rnw')} %quality control
\Sexpr{knit_child('lumi_limma.Rnw')} %differentially expressed genes
\Sexpr{knit_child('lumi_function.Rnw')} %functional analysis


\newpage


\printbibliography

\clearpage
\printindex

\end{document}

